apiVersion: v1
kind: Secret
metadata:
  name: backend-environment
  namespace: application
type: Opaque
data:
  JWT_SECRET_KEY: "c2VjcmV0"  # base64 encoded value of "secret"
  MINIO_HOST_PORT: "MTkyLjE2OC4xMS4xNDc6MzIxMTE="  # base64 encoded value of "192.168.11.147:32111" # Cần sửa
  MINIO_REGION: "YXAtc291dGhlYXN0LTE="
  MINIO_ACCESS_KEY: "bWluaW9hZG1pbg=="
  MINIO_SECRET_KEY: "bWluaW9hZG1pbg=="
  GOOGLE_CLIENT_ID: "ODE5NjM1MjYwMjQtbTBydDEwa2hlZ2sxZmljaTY4ZzdwdW51MXNwdXFuaHMuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20="  # base64 encoded value of your Google client ID
  ADMINIO_HOST_PORT: "OjgwODA="  # base64 encoded value of ":8080"
  DB_HOST: "bXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA=="  # base64 encoded value of "mysql.default.svc.cluster.local"
  DB_PORT: "MzMwNg=="
  DB_USER: "cm9vdA=="  # base64 encoded value of "root"
  DB_PASS: "YTEyMzQ1Ng=="  # base64 encoded value of "a123456"
  DB_NAME: "YWRtaW5pbw=="  # base64 encoded value of "adminio"
  ADMINIO_SWAGGER_HOST: "ZGF0YWxha2V2LXJlbGF5ZXIuc290YWljZy5jb20="  # base64 encoded value of "datalakev2-relayer.sotaicg.com"
  ADMINIO_SWAGGER_SCHEME: "aHR0cHM6Ly9kYXRhbGFrZXYyLXJlbGF5ZXIuc290YWljZy5jb20="
  REDIS_HOST: "MTkyLjE2OC4xMTQuMTQ3"  # base64 encoded value of "192.168.11.147"
  REDIS_PORT: "NjM3OQ=="
  MONGO_HOST: "bW9uZ29kYi1tb25nb2RiLXNoYXJkZWQuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA=="  # base64 encoded value of "mongodb-mongodb-sharded.default.svc.cluster.local"
  MONGO_PORT: "MjcwMTc="
  MONGO_USER: "cm9vdA=="  # base64 encoded value of "root"
  MONGO_PASS: "QWRtaW5fMTIz"  # base64 encoded value of "Admin_123"
  MONGO_DB_NAME: "ZGV2X2RhdGFmaWxlcw=="  # base64 encoded value of "dev_datafiles"
  ELASTIC_HOST: "ZWxhc3RpY3NlYXJjaC1tYXN0ZXIuZWxhc3RpYy1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWw="  # base64 encoded value of "elasticsearch-master.elastic-system.svc.cluster.local"
  ELASTIC_PORT: "OTIwMA=="
  MINIO_SSL: "dHJ1ZQ=="  # base64 encoded value of "true"
