# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - image: {{ .Values.deployment.image }}
        name: {{ .Values.deployment.name }}
        env:
          {{- range .Values.mysql }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
          name: {{ .Values.deployment.name }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: {{ .Values.deployment.volumeMountPath }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}

