# templates/persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  # storageClassName: nfsstorageclass
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
