---
- hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: ping
      ansible.builtin.ping:

    - name: Add information for /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - "192.168.11.147 EPC02"
        - "192.168.11.148 EPC03"
        - "192.168.11.149 EPC04"
        - "192.168.11.151 EPC05"
        - "192.168.11.152 EPC06"
        - "192.168.11.153 EPC07"
        - "127.0.0.1 localhost"

    - name: Turn off ufw for each machine
      ansible.builtin.command:
        cmd: sudo ufw disable

    - name: Turn off swap for each worker
      ansible.builtin.shell:
        cmd: sudo swapoff -a

    - name: Comment out swap partitions in /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^(.*swap.*)$'
        line: '#\1'

    - name: Ensure /etc/muodules-load.d/k8s.conf exists
      ansible.builtin.file:
        path: /etc/modules-load.d/k8s.conf
        state: touch

    - name: Configure persistent loading of modules
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "{{ item }}"
      loop:
        - overlay
        - br-netfilter

    - name: Ensure /etc/modules-load.d/crio.conf exists
      ansible.builtin.file:
        path: /etc/modules-load.d/crio.conf
        state: touch

    - name: Configure for CRIO
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/crio.conf
        line: "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Load at runtime
      ansible.builtin.shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter
    
    - name: Ensure /etc/sysctl.d/k8s.conf exists
      ansible.builtin.file:
        path: /etc/sysctl.d/k8s.conf
        state: touch
    - name: Ensure sysctl params are set
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item }}"
      loop:
        - "net.bridge.bridge-nf-call-ip6tables = 1"
        - "net.bridge.bridge-nf-call-iptables = 1"
        - "net.ipv4.ip_forward = 1"

    - name: Reload config
      ansible.builtin.command:
        cmd: sudo sysctl --system

