---
- hosts: localhost
  become: yes
  gather_facts: false
  connection: local

  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Initialize the cluster
      ansible.builtin.shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket unix:///var/run/crio/crio.sock >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      become_user: epc

    - name: Create a .kube directory
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: "0755"
      become: yes
      become_user: epc

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/epc/.kube/config
        remote_src: yes
        owner: epc

    - name: Install Pod network
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
      become: yes
      become_user: epc
