---
- hosts: localhost
  gather_facts: false
  become: true
  connection: local

  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      ansible.builtin.shell: "{{ hostvars['EPC02'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
